version: '3'

services:
  mysql:
    image: mysql:8.0.33
    container_name: cat-picture-db
    ports:
      - 3307:3306 # HOST:CONTAINER
    environment:
      MYSQL_ROOT_PASSWORD: example_password
      MYSQL_DATABASE : cat_api
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - /mysql/data:/var/lib/mysql